version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
        environment:
          - PLAYER_DATA_BIND=mysql+pymysql://root:daniel19982010@localhost/player_v_teams
          - KEY_BIND=mysql+pymysql://root:daniel19982010@localhost/keys
    redis:
        image: redis